### ISSUE TITLE
Build colored output

### ISSUE THREAD

**Issue by perigoso** [openinput-fw/openinput#100]
It would be nice to have colored output when building, it makes the output more readable and it's helpful for the developer.

We could just add the flag `-fdiagnostics-color`/`-fcolor-diagnostics` on every target or platform config, but this is rather irrelevant for the device itself, so in order to keep the configs cleaner, the build system could append these itself.

What do you think @FFY00 ?

For reference:
![image](https://user-images.githubusercontent.com/39195157/140768057-6d65271c-ef7c-4a2f-8db2-76ae1f8681fa.png)
![image](https://user-images.githubusercontent.com/39195157/140768203-57364a4f-cc5d-4af0-b328-0b5962a80f66.png)

**Comment by FFY00** [comment]
We can add `cflags`/`ldflags` fields to the base config.

**Comment by perigoso** [comment]
ah! yeah i forgot about that, definitely the correct approach
