### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by FFY00** [openinput-fw/openinput#17]
Looking at the `develop` branch, I came up with this structure.

```
src/
├── driver
│   ├── pixart
│   │   ├── pixart.h
│   │   └── truemove3.h
│   └── stm32f1
├── external
├── platform
│   └── stm32f1
├── protocol
├── targets
│   ├── linux-uhid
│   │   └── main.c
│   └── stm31f1
│       ├── config
│       │   ├── generic.h
│       │   └── rival310.h
│       └── main.c
└── util
```

Some notes.
- `driver/mcu` holds a directory for MCU families. If there is a need for some MCU specific code, a subdirectory can be created. If we just support the one MCU, and not a whole family, we can have a root directory for it.
- All external projects must go to `external`.
- `platform` should have a platform specific port of routines we may need in other parts of the code -- this is basically the abstraction layer.
- `protocol` should have a generic implementation of the protocol.
- `targets` holds a root directory for each target, each target should have a `main.c`. A target may have internal configs, this can be used to avoid having a whole new target for similar hardware.
- `util` should have generic C structures, utility routines, etc. that can be shared between the whole project.

Btw, `linux-uhid` would be a target that compiles to a native Linux binary and uses the UHID API to emulate a HID device. This could be used to test the project.

@perigoso what do you think?

**Comment by perigoso** [comment]
Looks good, but there are some things I don't love with my first stab at this, I'm looking to have a single `main` file, with higher level routine calls, a global `init` for drivers "high" level drivers, like the sensor, and then a platform/target dependent `startup` and `init` which init the actual device and peripherals. 
We should try to keep platform/target dependent code contained, that way It's easier to read and port to different devices.
I'm not sure how we'll handle target specific quirks, but ideally I imagine a code base that is common across all devices and a platform code that depends on the device, but we may not be able to do this cleanly.

**Comment by FFY00** [comment]
Hum, my problem with that is that the build systems will be much more complex. If you want for eg. just call `init_sensor()` in the generic main, we will have to know which sensor to init and how. The C preprocessor is not great for this kind of configuration. Well, it depends on where `init_sensor()` is defined... is it a generic function or defined by the target? Having this kind of abstraction might also make some other things a bit harder, like initing parts in a different order or in a weird way.

What I was envisioning was to have an abstraction for the lower level hardware, but not the targets themselves. Even because I might want to have a super specific target, for eg. an integrated laptop keyboard that talks I2C or SMBUS rather than USB.

So, if you are suggesting having a generic `init_sensor()`, I would say that this is really hard to do with the C preprocessor and it will become increasingly harder every time we introduce a little bit more complexity.

If you are suggesting having `init_sensor()` defined by the target, so that it can set up as it likes, I say that at the end of the day you are just ultimately calling a bunch of functions that the target defines anyway. If you were thinking of calling some other generic code there too, I'd say that there are targets where we may not want to do that.

Does that make sense?

**Comment by perigoso** [comment]
I wasn't clear, I wasn't looking for that much abstraction, but now that I think things through my idea didn't really make sense, not without relying a lot on the preprocessor, which I also don't love and wanted to avoid.

**Comment by perigoso** [comment]
I was envisioning something where you wouldn't have to mess with code other than config files to support a device, but that is not really viable for something as flexible as this should be.

**Comment by FFY00** [comment]
This can be closed now, as we have already implemented a structure, and so far it has been working fine.
