### ISSUE TITLE
Mismatched PMW SROM data may be uploaded

### ISSUE THREAD

**Issue by t-8ch** [openinput-fw/openinput#66]
`pixart_pmw_init()` will upload the passed in firmware to any detected PMW3360 or PMW3389 chip.

If for some reason the config does not match the actual running hardware this would mean that the wrong SROM blob could be uploaded.

**Comment by perigoso** [comment]
The sensor itself does verification afterwards, it will fail the initialization, proper verification is yet to be implemented, no harm is done to the hardware, its a soft fail
